---
default_install_hook_types:
  - pre-commit
  - pre-push
repos:
  - repo: https://github.com/doublethink13/pre-commit-git
    rev: 6edc744aca9362bfd3255608c485916042cca0af
    hooks:
      - always_run: true
        id: prevent
