---
- description: Prevent actions on specific branches
  entry: prevent_branch_actions
  id: prevent
  language: python
  language_version: python3
  name: prevent
  pass_filenames: false
  stages:
    - pre-commit
    - pre-push
  types:
    - python
